"""Initial

Revision ID: 441b1e756484
Revises: 
Create Date: 2025-07-23 15:03:37.880006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441b1e756484'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('created_at_ms', sa.BigInteger(), server_default=sa.text('(EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('capital_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('DEPOSIT', 'WITHDRAW', name='capital_action_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), server_default=sa.text('(EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT'), nullable=True),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdrawal_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='withdrawal_status_enum'), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), server_default=sa.text('(EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT'), nullable=True),
    sa.Column('decided_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal_request')
    op.drop_table('capital_history')
    op.drop_table('users')
    # ### end Alembic commands ###
